name: Build

on:
  push:
  workflow_dispatch:

env:
  PGUSER: postgres
  PGPASSWORD: postgres
  PGDATABASE: postgres
  PGHOST: localhost
  POSTGRES_REP_USER: reptest
  POSTGRES_REP_PASSWORD: reptest
  PACT_BROKER_BASE_URL: http://0.0.0.0:8000
  PACT_BROKER_USERNAME: pact_workshop
  PACT_BROKER_PASSWORD: pact_workshop

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: "Installing Pact CLI Tools"
        run: |
          echo "Installing Pact CLI Tools"
          echo "=> downloading Pact CLI Tools"
          os='linux-x86_64'
          tag=$(basename $(curl -fs -o/dev/null -w %{redirect_url} https://github.com/pact-foundation/pact-ruby-standalone/releases/latest))
          filename="pact-${tag#v}-${os}.tar.gz"
          standalone_download_path=https://github.com/pact-foundation/pact-ruby-standalone/releases/download/${tag}/${filename}
          echo "from ${standalone_download_path}"
          curl -LO ${standalone_download_path}
          tar xzf ${filename}
          rm ${filename}
          echo "PATH=${PATH}:${PWD}/pact/bin/" >> $GITHUB_ENV
      - run: pact help
      - name: Start OSS Pact Broker
        run: docker-compose up -d pact-broker
      - name: Start docker pg
        run: make docker_pg
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: make install_integration
      - run: make test_integration
      - run: make install_pact_js
      - run: make test_pact_js_consumer
      - run: pact-broker publish pacts --auto-detect-version-properties --consumer-app-version $(git rev-parse HEAD)
        working-directory: message_pact_js
      - run: make test_pact_js_provider
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: make install_pact_python
      - run: make test_pact_python_consumer
      - run: pact-broker publish pacts --auto-detect-version-properties --consumer-app-version $(git rev-parse HEAD)
        working-directory: message_pact_python
      - run: make test_pact_python_provider
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.4'
      - run: make install_pact_ruby
      - run: make test_pact_ruby_consumer
      - run: pact-broker publish pacts --auto-detect-version-properties --consumer-app-version $(git rev-parse HEAD)
        working-directory: message_pact_ruby/specs
      - run: make test_pact_ruby_provider
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: make test_pact_net_consumer
      - run: pact-broker publish pacts --auto-detect-version-properties --consumer-app-version $(git rev-parse HEAD)
        working-directory: message_pact_net/Consumer.Tests
      - run: make test_pact_net_provider
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' 
          java-version: '11'
      - run: make test_pact_java_consumer
      - run: pact-broker publish pacts --auto-detect-version-properties --consumer-app-version $(git rev-parse HEAD)
        working-directory: message_pact_java/consumer/build
      - run: make test_pact_java_provider
      - name: Stop docker
        if: always()
        run: docker-compose down